### ISSUE TITLE
 Login Logout 

### ISSUE THREAD

**Issue by linuxhjkaru** [thangninh1301/sample-ruby-app#1]
Hiện tại phải đăng ký nick mới bằng email.
Tuy nhiên anh muốn thêm login logout bằng fb và google.
Trên form login hiện tại thêm 2 button login bằng Facebook và Google.

**Comment by thangninh1301** [comment]
Em đã làm xong login bằng gg,fb ( có sẵn trong repo github).
missing: Test login với rspec
Estimate time: 4h
Task 1: login bằng gg,fb.

Sử dụng omniauth, devise để xác nhận, sử dụng Figaro để lưu key,id trong môi trường dev
Thời gian dự kiến : 8h
