### ISSUE TITLE
Thêm comment cho post

### ISSUE THREAD

**Issue by linuxhjkaru** [thangninh1301/sample-ruby-app#16]
Thêm phần comment cho mỗi post.
Design sẽ giống như facebook. Bên dưới post hiển thị các comment cũ và chỗ nhập comment mới + hiển thị reaction.

**Comment by thangninh1301** [comment]
Mô tả yêu cầu:
- Có reaction
- Có content
- Có avartar người cmt
- Thời gian cmt
- Chỗ nhập cmt mới.
- Cmt trong cmt
- Load more cmt
- Xoá cmt
